//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDmsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_Comodities
    {
        public int ComoditiesID { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public string ShorName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> SpecificationsID { get; set; }
        public Nullable<decimal> RecPrice { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> SalPrice { get; set; }
        public string Barcode { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsValid { get; set; }
    }
}
