//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDmsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bas_Customer
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string LinkMan { get; set; }
        public string LinkManPhone { get; set; }
        public string Region { get; set; }
        public string QQ { get; set; }
        public string Wechat { get; set; }
        public string FAX { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<int> IsValid { get; set; }
        public string Remark { get; set; }
    }
}
