//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDmsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_SubControls
    {
        public int SubControlID { get; set; }
        public Nullable<int> ControlID { get; set; }
        public string SubControlName { get; set; }
        public string Type { get; set; }
        public string Prop { get; set; }
        public string Label { get; set; }
        public string Width { get; set; }
        public string Align { get; set; }
        public string TempateControls { get; set; }
        public string TempateIcons { get; set; }
        public string TempateEvents { get; set; }
        public string Describe { get; set; }
        public Nullable<int> TemplateID { get; set; }
    }
}
