//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDmsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Control11111
    {
        public int ControlID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string URL { get; set; }
        public string ControlName { get; set; }
        public string describe { get; set; }
    }
}
