//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDmsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_dictionarydata
    {
        public int dictdata_Id { get; set; }
        public string dictdata_Table { get; set; }
        public string dictdata_Field { get; set; }
        public string dictdata_Name { get; set; }
        public string dictdata_Value { get; set; }
    }
}
