//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDmsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Template
    {
        public int ID { get; set; }
        public string TemplateName { get; set; }
        public string ControlName { get; set; }
        public string Ref { get; set; }
        public string Attributes { get; set; }
        public string FindUrl { get; set; }
        public string FormUrl { get; set; }
        public string SaveUrl { get; set; }
        public string Prop { get; set; }
        public string Label { get; set; }
        public string Width { get; set; }
        public string ItemAttributes { get; set; }
        public string ButtonIcon1 { get; set; }
        public string ButtonIcon2 { get; set; }
        public string ButtonIcon3 { get; set; }
        public string Describe { get; set; }
    }
}
