//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webDmsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Button
    {
        public int BtnID { get; set; }
        public string BtnName { get; set; }
        public string BtnNo { get; set; }
        public string BtnClass { get; set; }
        public string BtnIcon { get; set; }
        public string BtnScript { get; set; }
        public string MenuNo { get; set; }
    }
}
